/**
 * AI Features Hook
 * Uses backend provider integrations instead of renderer mocks.
 */

import { useCallback, useMemo, useState } from 'react';

import { trpc } from '@/trpc/client';

interface AICommitSuggestion {
	message: string;
	description: string;
	confidence: number;
}

interface UseAIFeatures {
	isGeneratingMessage: boolean;
	generateCommitMessage: (stagedFiles: string[], diff: string) => Promise<AICommitSuggestion | null>;
	lastSuggestion: AICommitSuggestion | null;
	isComposingSeries: boolean;
	composeCommitSeries: (changes: Array<{ files: string[]; diff: string }>) => Promise<string[]>;
	isAnalyzingConflict: boolean;
	suggestConflictResolution: (conflictContent: string) => Promise<string | null>;
	isAIEnabled: boolean;
	setAIEnabled: (enabled: boolean) => void;
}

export function useAIFeatures(): UseAIFeatures {
	const [lastSuggestion, setLastSuggestion] = useState<AICommitSuggestion | null>(null);
	const [isComposingSeries, setIsComposingSeries] = useState(false);

	const configQuery = trpc.ai.getConfig.useQuery(undefined, { staleTime: 10_000 });
	const setConfigMutation = trpc.ai.setConfig.useMutation();
	const commitMutation = trpc.ai.generateCommitMessage.useMutation();
	const conflictMutation = trpc.ai.explainConflict.useMutation();

	const isAIEnabled = Boolean(configQuery.data?.enabled);

	const setAIEnabled = useCallback(
		(enabled: boolean) => {
			setConfigMutation.mutate({ enabled });
		},
		[setConfigMutation]
	);

	const generateCommitMessage = useCallback(
		async (stagedFiles: string[], diff: string): Promise<AICommitSuggestion | null> => {
			if (!isAIEnabled) {
				return null;
			}

			const result = await commitMutation.mutateAsync({ stagedFiles, diff });
			if (!result.suggestion) {
				return null;
			}

			const suggestion: AICommitSuggestion = {
				message: result.suggestion,
				description: result.error ? `Fallback used: ${result.error}` : 'Generated by configured AI provider.',
				confidence: result.error ? 0.55 : 0.86,
			};
			setLastSuggestion(suggestion);
			return suggestion;
		},
		[commitMutation, isAIEnabled]
	);

	const composeCommitSeries = useCallback(
		async (changes: Array<{ files: string[]; diff: string }>): Promise<string[]> => {
			if (!isAIEnabled || changes.length === 0) {
				return [];
			}

			setIsComposingSeries(true);
			try {
				const suggestions: string[] = [];
				for (const change of changes) {
					const result = await commitMutation.mutateAsync({
						stagedFiles: change.files,
						diff: change.diff,
					});
					suggestions.push(result.suggestion ?? `chore: update ${String(change.files.length)} file(s)`);
				}
				return suggestions;
			} finally {
				setIsComposingSeries(false);
			}
		},
		[commitMutation, isAIEnabled]
	);

	const suggestConflictResolution = useCallback(
		async (conflictContent: string): Promise<string | null> => {
			if (!isAIEnabled) {
				return null;
			}

			const result = await conflictMutation.mutateAsync({
				filePath: 'conflicted-file',
				conflictContent,
			});

			if (!result.explanation) {
				return null;
			}

			const suggestions = result.suggestions.length > 0 ? `\n- ${result.suggestions.join('\n- ')}` : '';
			return `${result.explanation}${suggestions}`;
		},
		[conflictMutation, isAIEnabled]
	);

	return useMemo(
		() => ({
			isGeneratingMessage: commitMutation.isPending,
			generateCommitMessage,
			lastSuggestion,
			isComposingSeries,
			composeCommitSeries,
			isAnalyzingConflict: conflictMutation.isPending,
			suggestConflictResolution,
			isAIEnabled,
			setAIEnabled,
		}),
		[
			commitMutation.isPending,
			conflictMutation.isPending,
			composeCommitSeries,
			generateCommitMessage,
			isAIEnabled,
			isComposingSeries,
			lastSuggestion,
			setAIEnabled,
			suggestConflictResolution,
		]
	);
}
